### ISSUE TITLE
Changes in RST files not shown in English version, but shown in localized pages.

### ISSUE THREAD

**Issue by gab3d** [opentoonz/opentoonz_docs#126]
@shun-iwasawa 
I've introduced changes in the **whats_new.rst** file, for the Highlights of v1.6.
Those changes are visible in Spanish, Russian and Japanese versions but not in the English page.
It escapes me what's the reason for this behavior. 🤔

**Comment by shun-iwasawa** [comment]
The HTML build had been failed with the message `Concurrency limit reached (2)` .
I re-ran the build and now it is properly updated. Thank you!

**Comment by gab3d** [comment]
Thank you!
