### ISSUE TITLE
I want to contribute screenshots and gifs

### ISSUE THREAD

**Issue by FerrLui** [opentoonz/opentoonz_docs#13]
I want to contribute in making the Opentoonz user manual more user friendly, as Orphanlast suggested. How do I apply them onto a page so that I can get straight to work?

**Comment by gab3d** [comment]
@FerrLui 
Hi, and welcome! :)
1. You first have to have the right to commit into the manual repository (@shun-iwasawa will be able to give it to you).
2. Then log into Github
3. Google for the OT manual, and then go to the section you want to contribute to. At the top right press the "Edit on GitHub" hyperlink (I usually do a Ctrl + click or MMB click so it opens in another tab, and still preserve the manual for revieweing what I'm doing more easily).
4. One on the GitHub page corresponding to the manual page you want to edit, press the Pencil Icon (next to the trashcan icon). This will allow you, both, to edit the text in that section, as well as adding references to images previously uploaded to the GitHub site (*more on that later).
5. Scroll to the very end of that text. There you will see a list of (relative) image paths, as well as a name after wich they could be referenced inside the manual text.
For example:
.. |UI_rooms| image:: /_static/UI/UI_rooms.png
this declares that an image file called "UI_rooms.png" exists in the path "/_static/UI/", and could be referenced in the text as "|UI_rooms|".

you can add as many lineas as this one as you like and then reference that image inside that manual page, as many times as you want.

When you finish your editinf you Commit Changes and go to the original manual page to reload it and see how it looks there.


* Of course you should previously upload the image to some path inside the GitHub repository for this to work.
Ideally in the  /_static/  directory there should be folders for each manual section and the images should be inside that folders, to preserve the sanity of the structure. It is also a good idea to name the images with names that reflect what they illustrate.

Good luck and I am at your disposal for anything else you might need.

**Comment by FerrLui** [comment]
Thank You.I start to work)
