### ISSUE TITLE
proposed change to Makefile to make Anaconda optional

### ISSUE THREAD

**Issue by yehjaemin** [opentoonz/opentoonz_docs#32]
I'm sorry if this seems unnecessary, but I've used Sphinx before without Anaconda to build pages and after some testing I figured out that if you change line 6 in Makefile from ```python -msphinx``` to ```sphinx-build```, you can run ```make html``` in the command line, making the use of Anaconda optional for building locally.

Anaconda isn't even a particularly heavy program, so I thought it might be best to propose this change as an issue rather than a PR. If people generally like this idea though, I'd like to submit a pull request.

**Comment by WolfInABowl** [comment]
Sure, this sounds like a good idea; anything to simplify the build process is helpful.
