### ISSUE TITLE
Organization of Sidebar

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz_docs#54]
Hi! Thanks for all of the great work updating the manual! I'm wondering if the sidebar could be organized to be even more accessible for new OT users. I think installing FFMPEG is something people should do directly after installing OT, so that they are setup for video rendering from the beginning. Perhaps under "Getting Started" after "Installing OpenToonz", FFMPEG could be added instead. I do think there needs to be a more descriptive heading - many users won't know what FFMPEG is.

Getting Started
- Installing OpenToonz
- Enable video formats and more with FFMPEG

**Comment by gab3d** [comment]
Agreed. 👍 
I've already changed the position to the Getting Started chapter.

As for the title of the page, it'd be good if is kept short.
Perhaps just **Installing FFmpeg** would do, or **Installing and configuring FFmpeg** ?? (not so short, I know).

**Comment by artisteacher** [comment]
Wow, that was fast! Maybe the change in location will be enough? It is tricky making the name more descriptive without making the name too long.

Would it make sense to have a couple more parent categories, just for easier readability? 
For instance, version control and the farm are additional features that are not already setup in OT upon installation. They might not really belong under "Getting Started" but could be placed in an additional section at the end for Add-ons or something?

**Comment by gab3d** [comment]
> Wow, that was fast!

...and furious! 😄 

> Would it make sense to have a couple more parent categories, just for easier readability?
For instance, version control and the farm are additional features that are not already setup in OT upon installation. They might not really belong under "Getting Started" but could be placed in an additional section at the end for Add-ons or something?

yeah.. probably, or something "Advanced blahblah"...

**Comment by artisteacher** [comment]
Advanced Configuration?
