### ISSUE TITLE
Additional FFmpeg installation step for macOS Catalina

### ISSUE THREAD

**Issue by artisteacher** [opentoonz/opentoonz_docs#85]
A new step for the FFmpeg installation needs to added for macOS Catalina (10.15)
> Insert the path to your FFmpeg folder that you created earlier, if you have used the recommended path, this will be /Applications/OpenToonz/FFmpeg:

For macOS 10.15 and later, each executable within the FFmpeg folder needs to be opened once before using OpenToonz (this only needs to be done one time, due to new security features). In Finder, right-click and select "Open With -> Terminal". Once the Terminal windows have launched successfully, Terminal can be closed.
<img width="516" alt="Screen Shot 2019-11-19 at 8 42 56 PM" src="https://user-images.githubusercontent.com/21159116/69201698-329f4300-0b0d-11ea-8c8a-297b8752b698.png">

> Restart OpenToonz.

**Comment by artisteacher** [comment]
On a related note, as of macOS 10.15, opening the OpenToonz installer also requires right-clicking on the installer in Finder to open. The first time a new OpenToonz installation is run, it must be opened by right-clicking on the app in Finder.

Right-clicking on an app/executable in Finder overrides Gatekeeper security which blocks non-apple developer apps by default.

**Comment by artisteacher** [comment]
#96

**Comment by RodneyBaker** [comment]
Tangentally related:
According to https://github.com/opentoonz/opentoonz/pull/6240 FFMPEG will now be found automatically if present and stored in the operating system's environmental variables.   While it uses slightly different methods for different OS's it should work.
